player-status-option:
  maxHealth: 40    # 玩家的默认最大血量
player-spawn-option:
  range:
    min: 500    # 散布的最大范围(正方形半边长)
    max: 1750    # 散布的最大范围(正方形半边长)
  radius: 1500    # 散布的目标距离(圆形半径)
  min-relative-space: 500    # 散布点间的最小距离(直线距离)
  calculating-times: 512    # 散布时的尝试数(较低的尝试数易导致散布失败, 较高易导致服务器卡顿)
worldborder-option:
  damage:
    amount: 1    # 世界边界伤害
    buffer-distance: 0    # 世界边界伤害缓冲区
  warning-distance: 8    # 世界边界预警距离
  radius:
    min: 64    # 世界边界最小半径(圆形半径)
    max: 2048    # 世界边界初始半径(圆形半径)
  shrink-speed: 1    # 世界边界收缩速度(圆形半径)
  shrink-accelerating-option:
    enabled: True
    activate-item: IRON_BLOCK    # 激活加速收缩的物品(需为严格Material名)
    speed: 1    # 世界边界加速倍率
    duration: 1200    # 世界边界加速收缩有效时间
    cool-down: 300    # 加速冷却时间(ticks)
    beginning-protect-time: 6000    # 初始保护时间(ticks)
game-misc-option:
  protect-animal: True    # 动物是否免疫一切伤害
  ore-auto-melt: False    # 挖掘矿石时, 是否直接掉落矿物锭
  hide-playername: True    # 事件发生时是否显示玩家名(对控制台记录无效)
  game-preparing-time: 30    # 游戏加载的准备时间
  compass-option:
    enabled: True
    mode: True    # 使用指南针的方式(true: 右键交互; false: 丢出)
    cool-down: 100    # 指南针冷却时间(ticks)
    summon-blaze: True
  deathmatch: True

# 若要自定义配置文件, 请复制上方全部内容, 改变一级列表名
# 如:
# custom-config: 
#   player-spread-option: 
# ......
# 然后在准备游戏时使用指令 
# /battleroyale preset [worldName] [configName]
# 如:
# /battleroyale preset overworld custom-config
# 以使用该配置